name: Release-alpha

on:
  workflow_run:
    workflows: [Run Unit Tests]
    types:
      - completed
    branches:
      - alpha

jobs:
  on-success:
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Debug Workflow Run
        run: |
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow Run Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow Run Head Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Workflow Run Event: ${{ github.event.workflow_run.event }}"
          echo "Workflow Run Status: ${{ github.event.workflow_run.status }}"

      - run: echo 'All tests passing, preparing release...'

      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
